### ISSUE TITLE
Display each section in a buffer

### ISSUE THREAD

**Issue by xiongtx** [wasamasa/nov.el#11]
## Expected Behavior

Each _section_ is displayed in a buffer, and the user can advance by section in addition to by chapter.

This would be similar to how Info treats nodes.

## Actual Behavior

Only chapters can be displayed in a buffer.

**Comment by wasamasa** [comment]
The problem with this is that sections aren't a thing in the first place.  Just because the TOC links to parts of the document doesn't mean it comes sliced into sections.  For this to work you'd need to do that kind of splitting yourself, change the internal representation so that switching between sections in a document is supported and make sure metadata (currently the `<title>` tag) is included in each slice.  For me this is not worth the effort, I'd rather look for a simpler solution like remembering the last position in the document and restoring it to make reading more convenient.
