### ISSUE TITLE
Feature request: collapsible TOC

### ISSUE THREAD

**Issue by srustamo** [wasamasa/nov.el#16]
Collapsible TOC would help with very large TOCs.

**Comment by wasamasa** [comment]
How exactly would this help? Do you have an example of a document with a very large TOC? If this were about a feature like searchable TOCs (which is not needed because by the virtue of a TOC being displayed in a buffer you can simply use `C-s`) I'd agree, but folding is mostly a gimmick to me which slows down Emacs for little gain.  Also, did you try using an existing package such as yafolding which folds based on the indentation depth to check whether folding in its current form in Emacs works out for you?

**Comment by srustamo** [comment]
A sample of a deeply structured TOC can be seen in this book: http://www.gutenberg.org/ebooks/28054

Typically any tech book will have a deeply structured TOC. Below is a screenshot of how it is implemented in Caliber's E-reader. 

I tried yafolding, and it gets the job done. Albeit a bit too slow and based on indentation only. I wonder if all EPUB TOCs are indented.

![scr](https://user-images.githubusercontent.com/749813/30276773-506d0926-971f-11e7-9037-79b18f5bbb9a.jpg)

**Comment by wasamasa** [comment]
Yes, if hierarchies are represented using `<ol>` or `<ul>`, they will be rendered indented and therefore work with a folding package using indentation. Therefore I'm closing this.
