### ISSUE TITLE
nov-display-metadata non-string isbn

### ISSUE THREAD

**Issue by dwhoman** [wasamasa/nov.el#21]
When issuing nov-display-metadata on an epub file, the identifier property returns a symbol, in this case urn:isbn:9781449328009.  I got it to work by putting (format "%s" value) before the insert to guarantee that the type is correct.  The fix could go in nov-content-metadata if you intend nov-metadata to be an alist of (symbol . string).

nov-metadata for the particular epub looks like:
((identifier . urn:isbn:9781449328009)
 (title . "Database Design and Relational Theory")
 (language . "en")
 (contributor)
 (coverage)
 (creator . "C.J. Date")
 (date . "2012-04-19")
 (description . "<p>What makes this book different from others on database design? Many resources on design practice do little to explain the underlying theory, and books on design theory are aimed primarily at theoreticians. In this book, renowned expert Chris Date bridges the gap by introducing design theory in ways practitioners can understand&#8212;drawing on lessons learned over four decades of experience to demonstrate why proper database design is so critical in the first place.</p>")
 (format)
 (publisher . "O'Reilly Media")
 (relation)
 (rights . "Copyright © 2012 Chris Date")
 (source)
 (subject . "COMPUTERS / Database Management / General")
 (type))

**Comment by wasamasa** [comment]
I don't actually, while most of the values are strings, some are `nil` (because they're unset) and the identifier one is a symbol (as it's used for lookup in the last places file). The right thing to do here would be to always insert values as strings.  Can't believe I've overlooked this so far...

A minor problem here is that the `urn:isbn:` part ought to be stripped, much like `urn:uuid:`, but I'm less sure about that.  Stripping both might introduce collisions, undoing the stripping would ruin saved places...
