### ISSUE TITLE
Question on Adobe DRM

### ISSUE THREAD

**Issue by nmsalgueiro** [wasamasa/nov.el#22]
Thank you for this excellent mode for Emacs. I've been using it to read EPUBs from Project Gutenberg, but now I'm ready to buy a few EPUBs that have this Adobe DRM. Can such books be opened/read in nov.el?
Thank you very much for your time!

**Comment by wasamasa** [comment]
This is not supported and I don't plan on supporting it.

IMO, you're best off *not* buying books using DRM or if you can't avoid it, removing the DRM yourself.  There are plenty guides on the internet on how this can be done. I consider DRM a major headache that serves no other benefit than keeping lawyers happy and everyone else unhappy.

edit: This might have come across as purely ideological which wasn't my intention.  The purpose of Adobe's DRM scheme is to heavily restrict who can read the book.  This requires using their proprietary SDK and identifying users by making them authenticate against Adobe servers.  Even if I wanted to support this I most likely couldn't because this system has been purely designed for the big players.  Breaking DRM is therefore out of scope for this project.

**Comment by nmsalgueiro** [comment]
I agree, DRM is absolutely horrible. I'll try to steer clear of it as much as possible, but for some titles it's looking nearly impossible. Much appreciated for your prompt feedback, and again thank you so much for your work!
