### ISSUE TITLE
Confusing little square boxes seen in epub

### ISSUE THREAD

**Issue by kaushalmodi** [wasamasa/nov.el#3]
Hi,

Thank you very much for working on this package! I can now finally start reading technical ebooks in emacs too! 

I tried this package on the book I am reading right now (Nim in Action). Overall, `nov.el` does an awesome job. The only thing that stands out is the presence of these big gray boxes through the whole book. I do not understand what element in the .epub renders to those boxes. But this screenshot might give you a better idea (the yellow highlighting is done by me to match the lines I could correlate between the raw and rendered epub):

![image](https://user-images.githubusercontent.com/3578197/30119785-d29d0d3a-92f4-11e7-95d4-95c832352d09.png)

**Comment by wasamasa** [comment]
Huh, this is weird, I've expected it to be about a missing picture, but judging from the source view it's something about the table.  The rendering is done by `shr.el` which suggests that its table rendering is far from perfect, you might be able to figure out more by doing `M-x describe-char` with point on the rectangle.  Alternatively, send me the EPUB file so that I can take a closer look at it.

**Comment by wasamasa** [comment]
Hm, I can't repro the problem, I get slightly different rendering instead with an alt text instead of a gray rectangle.  I'm on 25.2, IIRC you're on master.  Judging from the sources `shr-tag-table` tries rendering images *outside* the table and does so with `shr-tag-img` instead of using `nov-render-img` as specified in the overrides.  The reason why I do this override is because `shr-tag-img` isn't able to deal with relative file paths, so it's annoying if it isn't applied in this situation.  Now, the difference between our setups might be what image loader is used, I recall that the imagemagick loader is able to render error images if it can't resolve a path in a SVG, that might explain the problem.

**Comment by kaushalmodi** [comment]
Thanks for checking.

> IIRC you're on master

Yes, on latest master as of today.

Here's my Emacs build info if the Features list helps:

```
Emacs version: GNU Emacs 26.0.50 (build 6, x86_64-pc-linux-gnu, GTK+ Version 2.24.23)
 of 2017-09-06, built using commit 01a82957d25e7fc3fe4ec799f3c05f22a4278428.

./configure options:
  --with-modules --prefix=/home/kmodi/usr_local/apps/6/emacs/master '--program-transform-name=s/^ctags$/ctags_emacs/' 'CPPFLAGS=-I/home/kmodi/usr_local/6/include -I/usr/include/freetype2 -I/usr/include' 'CFLAGS=-ggdb3 -O0' 'CXXFLAGS=-ggdb3 -O0' 'LDFLAGS=-L/home/kmodi/usr_local/6/lib -L/home/kmodi/usr_local/6/lib64 -ggdb3'

Features:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 MODULES
```

I looked at the shr.el changes on master: http://git.savannah.gnu.org/cgit/emacs.git/log/lisp/net/shr.el

![image](https://user-images.githubusercontent.com/3578197/30123579-8414a5f4-9300-11e7-8b23-13509fc60644.png)

There are quite a few commits related to shr-image and SVG.

**Comment by kaushalmodi** [comment]
I missed replying to this:

> you might be able to figure out more by doing M-x describe-char with point on the rectangle

![image](https://user-images.githubusercontent.com/3578197/30124474-4393db32-9303-11e7-8c7c-3e3a3c3c0ca4.png)

and interestingly that *display* property is:

```el
(image :type svg :data "<svg width=\"100\" height=\"100\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"> <defs> <linearGradient id=\"background\" x1=\"0\" x2=\"0\" y1=\"0\" y2=\"1\"> <stop offset=\"0%\" stop-color=\"#b0b0b0\"></stop> <stop offset=\"100%\" stop-color=\"#808080\"></stop></linearGradient></defs> <rect width=\"100\" height=\"100\" x=\"0\" y=\"0\" x1=\"0\" x2=\"0\" y1=\"0\" y2=\"1\" fill=\"url(#background)\" stroke=\"black\" stroke-width=\"2\"></rect></svg>" :scale 1 :ascent 100)
```

So that explains that square (need to yet figure out why that happens) .. [[Wild guess][1]]

and *image-displayer* is:

```el
(lambda
  (url start end)
  (when url
    (if
        (string-match "\\`cid:" url)
        nil
      (url-retrieve url 'shr-image-fetched
                    (list
                     (current-buffer)
                     start end)
                    t t))))
```

[1]: http://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/net/shr.el?id=e33ddda3bfb134756ae1a706bf8ea218c7312f2d

**Comment by wasamasa** [comment]
I went through `shr-tag-img` on master and discovered what is going on.  After passing lots of edge cases it inserts a placeholder image (which is a SVG with a gradient in it) and sets up a callback for it to be replaced with the actual image fetched by `url.el`.  Considering that images in EPUBs tend to be locally stored, the gradient will never be replaced and stays there.  Wonderful, isn't it?

**Comment by wasamasa** [comment]
I also reported a bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28402

**Comment by kaushalmodi** [comment]
I confirm the fix. Thank you!

![image](https://user-images.githubusercontent.com/3578197/30245482-f16ca14c-95a8-11e7-9bcb-f920ce612171.png)

**Comment by kaushalmodi** [comment]
Closing the loop :)

http://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-26&id=e3f4b71c9de72bce59b4b7cb71627b626e82b573

**Comment by wasamasa** [comment]
Not quite, Lars isn't amused about the change, see the last few posts in the debbugs thread.
