### ISSUE TITLE
Query: using justify-kp/justification rendering with visual-fill-column

### ISSUE THREAD

**Issue by emacsomancer** [wasamasa/nov.el#31]
The example of using justify-kp with nov-el does not seem compatible with a solution like `visual-fill-column`, and so the only way of using it seems to be to manually resize the Emacs window in order to get a reasonable column-width. Is there any way of using justify-kp with something that restricts the column width?  [I've also submitted a query over at https://github.com/joostkremers/visual-fill-column/issues/29 ]

**Comment by wasamasa** [comment]
No idea. I gave up on visual-fill-column ever since it started miscalculating columns when margins are involved.  That aside, it doesn't make any sense to combine both. Either you do hard filling (like justify-kp does) or you let things wrap around an imaginary border (like visual-fill-column does).

**Comment by emacsomancer** [comment]
So is the only way of contolling the text width when using the justify-kp method described in the README to literally make the Emacs window smaller?

**Comment by wasamasa** [comment]
Yes.
