### ISSUE TITLE
Would be nice to accept more ebooks

### ISSUE THREAD

**Issue by jimwise** [wasamasa/nov.el#32]
Finding a lot of ebooks which are readable by ereader mode but not nov.el, but prefer nov.el overall.

Happy to provide an example file, if that helps.

Generally error is of the form:

`File mode specification error: (error Unique identifier not found by its name: ...)
`
Is it possible to recover gracefully in this case?

If not, can we at least not open the zip file as a binary file once parsing fails?

**Comment by wasamasa** [comment]
That's a sign that the EPUB is malformed, something you can easily prove with `epubcheck`. It's in the interest of your publisher to fix it because it prevents viewing the EPUB in standards-compliant viewers. You could fix it easily yourself by generating a UUID and editing the content file to use it.

The unique identifier is required and if the declared name doesn't show up in the file, it's impossible to tell what the unique identifier is.  You could try to fall back to the first identifier specified, but that would just be a guess and possibly yield something less than unique, like if there are multiple identifiers specified and the first one isn't unique at all or worse, if none are specified. This information is required to save and restore the last place.

I'm not sure about the binary comment. If I get such an error, I get a buffer with binary contents.

**Comment by jimwise** [comment]
Yes, I’m aware of that.  But...

These are commercially produced ePub files which other ereader software — including ereader mode — are able to display fine despite these missing attributes.   Nov-mode fails spectacularly, displaying 11 megabytes of binary zip file in the buffer.  

If nov-mode is, by design, only ever going to support perfectly formed ePub files, this will severely limit its usability as a general purpose ereader.   This would be a shame, as nov-mode is a lot more visually pleasing than the competition...

**Comment by wasamasa** [comment]
I think you're over-exaggerating a bit here. I do not require 100% HTML compliance or anything else that's notoriously hard to get right, this is about a few invariants in the EPUB spec nearly all EPUBs out there satisfy. From my personal collection of almost 200 EPUBs, none of them fail opening in nov.el.

As for the binary thing, that's an unfortunate side effect of making it a major mode. Erroring out in a major mode function while the buffer is set up leaves it in `fundamental-mode`. File handlers (like for ZIP files) would be an alternative, however there is no way to fall back to another file handler either, making their errors equally fatal.

**Comment by jimwise** [comment]
Yeah, I can’t comment on what number of epubs in the wild are affected by this.  I just know that I’ve got a couple which are, they’re commercial epubs that I can’t regenerate with fixed metadata, and they display fine in ereader mode. 

I’m fine with closing this as won’t fix — your call, obviously — just reporting that for my use case a more graceful handling of this would make nov-mode usable for me. 

Thanks,

Jim Wise
jwise@draga.com

Sent from my iPhone.
Digital signature available upon request.
