### ISSUE TITLE
Add nov-mode to auto-mode-alist With an Autoload Cookie

### ISSUE THREAD

**Issue by parhamdoustdar** [wasamasa/nov.el#42]
This is something that you may be aware of, but have decided not to include. If so, I'd love to know your reasoning.

It would be a nice little touch to have something like this in `nov-mode`:

```
;;;###autoload
(add-to-list 'auto-mode-alist (cons "\\.epub\\'" 'nov-mode))
```

This should remove the need for users to register the epub file format manually in their init file.

Thanks!

**Comment by wasamasa** [comment]
What if there were another EPUB mode doing the same thing? A small post-installation annoyance is better than having two modes fighting over precedence just because you installed both of them. See also https://blogs.msdn.microsoft.com/oldnewthing/20050607-00/?p=35413/ for a lengthier discussion in the context of Microsoft Windows
