### ISSUE TITLE
Keybinding to switch to archive-mode

### ISSUE THREAD

**Issue by dov** [wasamasa/nov.el#44]
Once nice feature in emacs is the ability to edit zip files directly. I use this e.g. to edit the css of an epub. But when activating nov mode for epub files, there is no longer a simple way of turning on archive mode for the buffer. I suggest to add a keybinding to nov to switch into `archive-mode` for the file.

**Comment by wasamasa** [comment]
Interesting, I've never used that feature and only viewed ZIP files to visit their contents. I suspect this is trickier to achieve than it sounds like because archive-mode uses a similar approach as nov-mode to transparently decode files: Both take a buffer after a file has been opened, then replace its original contents with something custom. Therefore you can't just call the function with the buffer, by that time the original contents will be gone.

**Comment by wasamasa** [comment]
```elisp
(defun nov-reopen-as-archive ()
  (interactive)
  (find-file-literally nov-file-name)
  (archive-mode))

(define-key nov-mode-map (kbd "a") 'nov-reopen-as-archive)
```

How about this?

**Comment by dov** [comment]
Nice!

Of course it doesn't solve the problem of how to do global search and replace in the epub and then go back to nov mode to see the result. But it is a good start. :-)

**Comment by wasamasa** [comment]
I've committed a slightly different version of this that takes into account that after issuing `find-file-literally`, the current buffer isn't necessarily changed to the returned one.
