### ISSUE TITLE
Different Font

### ISSUE THREAD

**Issue by Nebucatnetzer** [wasamasa/nov.el#5]
Is there a way to change the font for nov.el?
I changed the default font for testing but that didn't change the font in nov.el

**Comment by wasamasa** [comment]
Currently you can only customize the `variable-pitch` font.

**Comment by Nebucatnetzer** [comment]
What does this do?
A serif font would be really great for reading books :)

**Comment by wasamasa** [comment]
Sorry, I mean the `variable-pitch` face which uses a sans-serif family by default.

**Comment by wasamasa** [comment]
I've looked into this a bit further and came to the conclusion that while it's possible for me to override `shr-current-font` it will not have the desired effect as subsequent faces (such as the one for links) are *appended* to the face property list which means that if the first item disables underlining (like, the default face), you won't see any link.  I've therefore only added the option to disable variable-pitch fonts entirely and extended the README to cover font customization.

@larsmagne Is there a reason you're explicitly appending text properties in `shr-add-font`?  See http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/net/shr.el?id=d63123542ffd60dbec0c9038144329b99f0f1d65#n898 for the offending line.

**Comment by larsmagne** [comment]
Vasilij Schneidermann <notifications@github.com> writes:

> @larsmagne Is there a reason you're explicitly appending text properties in
> shr-add-font? See
> http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/net/shr.el?id=d63123542ffd60dbec0c9038144329b99f0f1d65#n898
> for the offending line.

Yes -- if you have <red>This text is red<blue>and now it's blue</blue>
and now it's red again</red> you want the "inner" tag to win, and since
they're applied in the order of the end tags, you have to append to
achieve that effect.

If I remember correctly.

-- 
(domestic pets only, the antidote for overdose, milk.)
   bloggy blog: http://lars.ingebrigtsen.no
