### ISSUE TITLE
Apostrophes show up as \222

### ISSUE THREAD

**Issue by Northcode** [wasamasa/nov.el#6]
Opened the book "Zen and the art of Motorcycle Maintenance" and all the apostrophes show up as \222.

Not really sure how to make this easily reproducible since I can't share the book here.
A lot of other ebooks either show up completely garbled or say "Invalid epub" even though they work fine in Calibre.

**Comment by wasamasa** [comment]
Hm, sounds like an encoding issue.  Truth to be told, I'm relying on Emacs guessing the encoding correctly instead of interpreting the document's encoding from its metadata.

Send me an email with an attachment or contact me on IRC with a link to the copy.  Please do the same for the others.

**Comment by Northcode** [comment]
Alright, what email should I send it to?

**Comment by wasamasa** [comment]
Check the sources, you should find it quickly :>

**Comment by wasamasa** [comment]
I've looked into documents that specify something else than utf-8 as encoding and found using their specified charset to give me worse results than just letting Emacs guess.  Your document must have been badly broken for Emacs to guess wrong, like by having both latin-1 and utf-8 contents.  I'll reopen this issue once I've gotten my hands on such a document, otherwise there's no way to improve the current situation.

**Comment by wasamasa** [comment]
I've meanwhile received the questionable document and as expected, its encoding is as messed up as described above.  Decoding the phrase "it's" with latin-1 gives me "itÂ\222s", with utf-8 "it\222s" and with cp1252 "itÂ’s". None of these is ideal, but neither are the sources, so tell wherever you got that thing from to author their EPUBs properly.

The other document shows a more interesting bug though (images not being rendered due to missing read permissions) which I'll be working on instead.

**Comment by Northcode** [comment]
Ok, thanks for looking into it 👍

**Comment by wasamasa** [comment]
I fixed the other bug meanwhile, many thanks for providing the documents!
