### ISSUE TITLE
Is it able to render the content nicely in Emacs?

### ISSUE THREAD

**Issue by c02y** [wasamasa/nov.el#7]
I like the navigate the epub file with shortcuts a lot, but this is package will be better if it can render the content nicely in Emacs.

1. margins
2. wrap long lines
3. change font
4. multiple color and style of fonts (defined in epub files)

**Comment by wasamasa** [comment]
I plan to add customizables for the default font and the rendering function.  This way you should be able to customize all of these.

**Comment by wasamasa** [comment]
I've looked a bit more into this, the problem here is that `shr.el` doesn't exactly come with many customizables to make this workable.  For example while you can change the `shr-default-font` variable temporarily, it won't affect all body text, most notably with `<h1>` and friends.  Ideally you'd need to change `shr.el` itself to properly support such a customization and add faces on top of the default text.  You'd be best off with just customizing the `variable-pitch` face.

Long lines are wrapped already by the window border.  By let-binding `shr-width` you can change the fill width.  I don't know what exactly you mean by margins, but I don't see why it wouldn't work with a hook and one of the many modes for prettifying text.  Finally, styles of the CSS kind have only rudimentary support.  Your best bet is having documents that use the semantically correct tags for the best possible rendering, but that's apparently a pipe dream.

I'll close this issue as soon as I've introduced customizables for the default font, width and rendering function (for those who don't like `shr.el`) and added notes to the README.

**Comment by c02y** [comment]
> I don't know what exactly you mean by margins

![page_margin_guide](https://user-images.githubusercontent.com/2135996/30201396-3860d8b8-94ad-11e7-8d80-257e9f40722e.jpg)

**Comment by wasamasa** [comment]
Use an existing minor mode for that, I don't plan on reinventing the wheel for this feature.

**Comment by Nebucatnetzer** [comment]
I found olivetti to work quite well for this. https://github.com/rnkn/olivetti
Maybe there's something better but I already had it installed anyway.

**Comment by wasamasa** [comment]
Sure, that's one I had in mind, I've explained another option in the README.  I'm closing this issue as all customizables announced have been implemented.
